// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVMK7dT6emC9c7ZujPMSVcRa4uZXS2Z9Q',
    appId: '1:354182993701:web:51231261770b75a0b96ccc',
    messagingSenderId: '354182993701',
    projectId: 'anahuacnews-dd9c0',
    authDomain: 'anahuacnews-dd9c0.firebaseapp.com',
    storageBucket: 'anahuacnews-dd9c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFG_fIeGjyxTcPhge2PKTokwCIXYrNGGA',
    appId: '1:354182993701:android:c1878c848806e6b5b96ccc',
    messagingSenderId: '354182993701',
    projectId: 'anahuacnews-dd9c0',
    storageBucket: 'anahuacnews-dd9c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB2iP4Qx023f_DWwmF0uoW6JSz3LLPAjA',
    appId: '1:354182993701:ios:58b3ca5d1eb815b1b96ccc',
    messagingSenderId: '354182993701',
    projectId: 'anahuacnews-dd9c0',
    storageBucket: 'anahuacnews-dd9c0.appspot.com',
    iosClientId: '354182993701-22g97a21l1bfljcvl1kptk43nhaanvcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.anahuacNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB2iP4Qx023f_DWwmF0uoW6JSz3LLPAjA',
    appId: '1:354182993701:ios:58b3ca5d1eb815b1b96ccc',
    messagingSenderId: '354182993701',
    projectId: 'anahuacnews-dd9c0',
    storageBucket: 'anahuacnews-dd9c0.appspot.com',
    iosClientId: '354182993701-22g97a21l1bfljcvl1kptk43nhaanvcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.anahuacNews',
  );
}
